[keymaps]

[keymaps.global]
workspace-mode = "cmd-w"
view-mode = "cmd-v"

[keymaps.workspace-mode]
workspace-create = "c"
workspace-cut = "shift-c"
workspace-next = "n"
workspace-previous = "p"

[keymaps.view-mode]
view-expand-rows = "e"
view-shrink-rows = "shift-e"
view-expand-columns = "u"
view-shrink-columns = "d"
view-scroll-down = "n"
view-scroll-up = "p"
