[keymaps]

[keymaps.global]
workspace-mode = "cmd-w"
view-mode = "cmd-v"
pop-mode = "esc"

[keymaps.workspace-mode]
workspace-create = "c"
workspace-delete = "shift-c"
workspace-next = "n"
workspace-previous = "shift-n"

[keymaps.view-mode]
view-expand-rows = "e"
view-shrink-rows = "shift-e"
view-expand-columns = "v"
view-shrink-columns = "shift-v"
view-scroll-down = "n"
view-scroll-up = "shift-n"
view-toggle-fullscreen = "."
